### PR TITLE
Making a few small initial changes.

### PR DESCRIPTION
**Pull request by sonyahanson**
This will be:
- fixed a change in how pandas works for xml2png4scans
- add xml2png_5 and xml2png_spectra to scripts
- divide examples folder into 'ipython notebooks' and 'scripts'

### CODE REVIEW

**Comment by jchodera** [comment]
We don't have any xml2png tests yet, do we?  Maybe we want to add some?

**Comment by sonyahanson** [comment]
After I get these quick updates done, I want to combine these four scripts into one and change them to use `platereader.py`. So maybe tests are premature? Or maybe not...

**Comment by jchodera** [comment]
No problem---go with that plan!

**Comment by sonyahanson** [comment]
I tested the scripts manually, so should be fine. Going to go ahead and merge if that's all right.

**Pull request merged**
