### PR TITLE
[WIP] Unifying and cleaning platereading 

### PR DESCRIPTION
**Pull request by sonyahanson**
Fixing this up a little up. Unifying data file reading functions to be used throughout assaytools. Right now 'platereader.py' exists, but is rarely used as its functionality is limited.

### CODE REVIEW

**Comment by sonyahanson** [comment]
Added `grant.py`, which for now just pulled all of the functions used to make the grant figures into one place.  Makes the grant figure ipynbs (now in their own folder in examples) a lot cleaner. Hopefully a sign of things to come.  This is an interim step to replacing `platereader.py` entirely.

**Comment by sonyahanson** [comment]
There are currently some straightup plotting functions in `grant.py` (eventually to replace `platereader.py`) which use a function that creates your dataframe without you explicitly having to make it. I was thinking of separating these and moving to `plots.py`, which is currently only used for the pymc plotting, and am not sure what makes sense here. `plots.py` seems pretty intense as is, and I think it was just a first rough pass to get things done..

**Comment by jchodera** [comment]
Awesome, thanks!

**Comment by sonyahanson** [comment]
Going to go ahead and merge this, even though I haven't separated out the plotting functions yet.

**Comment by jchodera** [comment]
OK!

**Pull request merged**
