### PR TITLE
Cleanup of example modeling notebooks

### PR DESCRIPTION
**Pull request by jchodera**
I've gone through the "Two Component Binding" notebook so far.

### CODE REVIEW

**Comment by jchodera** [comment]
OK, this should be ready to merge.

I've added a bit of error (sigma = 10 fluorescence units) to both experiments in the "Bayes with Modeled data" notebook, and made sure the `log_sigma` range nicely encompassed this (permitting up to 40 fluorescence unit `sigma`).  Sampling now proceeds smoothly, and the error in Kd goes from 7% to 1% as more data points are added in the region of interest.

**Comment by jchodera** [comment]
Whoops, I caught a stray check-in as well, but I think this was updated anyway.

**Comment by jchodera** [comment]
Take a look at the updated notebooks when you get a chance:
- [modeling binding](https://github.com/jchodera/assaytools/blob/update-examples/examples/binding-assay-modeling/Just%20Modeling%20-%20Two%20Component%20Binding.ipynb)
- [inference with PyMC](https://github.com/jchodera/assaytools/blob/update-examples/examples/binding-assay-modeling/Just%20Modeling%20-%20Bayes%20with%20Modeled%20data.ipynb)

Note that I _do_ get ~2 nM out of the PyMC now that I added noise of the appropriate form to the modeled experimental fluorescence data, rather than the 0.9 nM you were seeing.  It may be worth trying this with a few bootstrap replicates to verify that there is in fact no systematic bias, but I believe the bias was due to the use of a Gaussian output model with prior on `log_sigma` on data that had no Gaussian noise, which is fundamentally incorrect from a Bayesian standpoint.

**Comment by jchodera** [comment]
Just a reminder that this should be merged after inspecting the updated notebooks!

**Comment by jchodera** [comment]
How about merging these (nudge nudge)?

**Comment by jchodera** [comment]
@sonyahanson

**Comment by sonyahanson** [comment]
I will look at this some time this week when I have more time. I will reserve the right not to merge, and will explain why if this is the decision.

**Comment by jchodera** [comment]
OK!  We can talk over it if this would help.  I found several critical issues with the existing notebooks that caused the pathologies you described, and believe I have fixed them all.

**Comment by sonyahanson** [comment]
Thanks! Definitely good to talk through this. It certainly does seem like adding noise to the original modeled data fixed the problem. Was just chatting with other members of the lab about this, and am interested in a clarification: Seems like in theory perfect data shouldn't be a problem unless there is a prior that makes it impossible. If this is the case, what is the prior that requires this in our case, and why is it necessary that it is this way?

**Comment by jchodera** [comment]
The prior _does_ make it impossible to have zero error:

```
# Unknown experimental measurement error.
    log_sigma = pymc.Uniform('log_sigma', lower=-10, upper=3, value=0.0) 
    @pymc.deterministic
    def precision(log_sigma=log_sigma): # measurement precision
        return np.exp(-2*log_sigma)
```

Now, this could let it have "small" error, with `sigma` = exp(-10) ~ 4e-5, but with _no noise at all_, there is really no information from which to estimate `sigma`.

The other effect that I think is at play (that you might be able to see by playing with the magnitude of noise you add) is that as the noise level `sigma` drops, the likelihood function may become more and more peaked about the perfect parameters, meaning that it is very hard for the sampler to even _find_ the optimal parameters.  With some noise, there's a much broader region and gentler slope for the sampler to fall into.  Otherwise, it's like a golf course.

**Comment by jchodera** [comment]
Just realized this hasn't been merged yet!  Is there anything else I should do to clean this up?

**Pull request merged**
