### PR TITLE
Fixed exp() bug in plot.py

### PR DESCRIPTION
**Pull request by sonyahanson**
This fixes errors mentioned in #31 .

Also added the 'scratch' ipython notebooks that I was running when I found this error. These will be cleaned eventually.

### CODE REVIEW

**Comment by jchodera** [comment]
Woohoo!

**Comment by jchodera** [comment]
I haven't seen that travis error before:

```
======================================================================
ERROR: Failure: ImportError (libopenblas.so.0: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/assaytools/__init__.py", line 5, in <module>
    from assaytools import pymcmodels
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/assaytools/pymcmodels.py", line 13, in <module>
    import pymc
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

It must be some weird `pymc` conda package issue,

**Comment by sonyahanson** [comment]
Boooo.

**Comment by jchodera** [comment]
Merging, since this obviously is an improvement.  Will fix the travis issues separately (if it's something we can fix on our end).

**Pull request merged**
