### PR TITLE
[WIP] Fix travis failures

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Hm. Travis doesn't seem to be running now.

**Comment by jchodera** [comment]
Travis had been switched off. Reactivated!

**Comment by sonyahanson** [comment]
Should it be saying something other than 'All checks have failed' then?

**Comment by jchodera** [comment]
If you click on "Details", you see that it is failing because

```
Miniconda MD5 mismatch
```

which would seem to be a problem on the miniconda webserver side.

**Comment by sonyahanson** [comment]
It's green!

**Pull request merged**
