### PR TITLE
small update to xml2png plotting singlet assay

### PR DESCRIPTION
**Pull request by sonyahanson**
Small update to xml2png plotting for single wavelength assay.

@MehtapIsik mentioned that the Lstated was hardcoded into this plotting script in xml2png, so now this is plotted by 'column index'. Also changed the plotting to dots and matched the coloring scheme to other plots made by `assaytools`.

This is good to merge on my end, but it'd be great if someone else could check in case I've used an older version of matplotlib that doesn't work for others. @MehtapIsik, @bas-rustenburg, and @jchodera should all have this power (run `xml2png --type singlet_384 *.xml` on any single wavelength 384-well dataset we've collected).

### CODE REVIEW

**Comment by jchodera** [comment]
Why not add a travis test to do the same thing and make sure it never breaks?

You can add a simple command-line call to `xml2png` after this line:
https://github.com/choderalab/assaytools/blob/master/.travis.yml#L34

**Comment by sonyahanson** [comment]
All checks have passed!

**Comment by jchodera** [comment]
Woohoo!

**Comment by jchodera** [comment]
Feel free to merge.

**Comment by jchodera** [comment]
Whoops!

**Pull request merged**
