### PR TITLE
Adding quickmodel example and a new competition assay modeling notebook.

### PR DESCRIPTION
**Pull request by sonyahanson**
First, I'm adding quickmodel examples as suggested in #68.

### CODE REVIEW

**Comment by sonyahanson** [comment]
Have now added a better experimental modeling notebook for the competition assay that combines (1) John's old notebook that plays with imatinib concentration and (2) the competition grid notebook, which I think results in a more complete notebook to help us design competition assays.

https://github.com/choderalab/assaytools/blob/data_clean/examples/competition-fluorescence-assay/1c%20Simulating%20Experimental%20Fluorescent%20Competition%20Assay%20Data.ipynb

**Comment by sonyahanson** [comment]
I'm happy to merge this. @jchodera I've removed your imatinib concentration notebook in favor of this new one, let me know if you disagree with this course of action.

**Comment by jchodera** [comment]
Sure, looks great!

**Comment by sonyahanson** [comment]
Added two notebooks to examples:
- one which using our simple bayesian model to fit simulated data, so that we can see if we can reproduce some of the problems we're seeing with real data.
- and another which reproduces the improvement in information in fluorescence data when the protein concentration is decreased that Nick Levinson clued us in on last week.

nicksproteinconc

**Comment by jchodera** [comment]
Can we merge this PR in, @sonyahanson?

**Comment by jchodera** [comment]
Whoops, looks like you already said it was OK!

**Pull request merged**
