### PR TITLE
Making a few quick updates, clean-ups.

### PR DESCRIPTION
**Pull request by sonyahanson**
Making a few quick updates, clean-up commits to xml2png and quickmodel.

### CODE REVIEW

**Comment by sonyahanson** [comment]
The most recent commit changes how `quickmodel` writes out results in the commandline. @MehtapIsik mentioned this was confusing, as it was previously using `pymcmodels.show_summary` ([link](https://github.com/choderalab/assaytools/blob/master/AssayTools/pymcmodels.py#L789)), which doesn't use any of the 95% interval machinery we're now working with.

This is is now written explicitly in `quickmodel.py` (maybe to be transferred later) and outputs e.g.:
```
p38-Erlotinib-EF
MAP fitting cycle 5/5
Delta G (95% credibility interval after equilibration):
   -9.93 [-10.4,-9.31] k_B T
Delta G (mean and std after equil):
   -9.9 +- 0.328 k_B T
Kd (mean and std after equil):
   50.1 uM +- 18.2 uM
```

**Comment by MehtapIsik** [comment]
I like it. This output is much clearer. 

Is it possible to calculate 95% credibility interval for K_d?

**Comment by sonyahanson** [comment]
Yes, I will add this. Thanks!

**Comment by sonyahanson** [comment]
Change made. Output now looks like this:

```
p38-Erlotinib-EF
MAP fitting cycle 5/5
Delta G (95% credibility interval after equilibration):
   -9.84 [-10.2,-9.09] k_B T
Delta G (mean and std after equil):
   -9.79 +- 0.288 k_B T
Kd (95% credibility interval after equilibration):
   53.2 [35.4,113.2] uM
Kd (mean and std after equil):
   55.8 uM +- 20.3 uM
```

Going to go ahead and merge so that these changes can be used in upcoming fluorescence-assay-manuscript updates.

**Comment by sonyahanson** [comment]
This is already merged. Github seems to have messed up...

**Pull request closed without merging**
