### PR TITLE
Making a more general xml2png

### PR DESCRIPTION
**Pull request by sonyahanson**
Here will be an `xml2png.py` that now uses flags to select what your input data type is rather than using a completely different scripts. It's still not pretty, but it's slightly nicer to use, and it's now clearer how to make it nice if we ever wanted to. 

First commit was just some new singlet assay xml files, more to come.

### CODE REVIEW

**Comment by sonyahanson** [comment]
Added `xml2png.py` that now gives us quick images of singlets, and is just a single script now where you can select what type of file your analyzing with `--type ['spectra', 'singlet_96', 'singlet_384','scan']`.

**Comment by sonyahanson** [comment]
This is done. Will merge if no complaints and close #7. If anyone wants to test it example data are in `/examples/scripts/`.

**Comment by jchodera** [comment]
Looks good!  I was going to ask why you didn't add tests, but then I realized I only started adding the nosetests in my PR. Will get that fixed up and merged in over the weekend!

**Comment by jchodera** [comment]
In the meantime, please merge!

**Pull request merged**
