### PR TITLE
[WIP] Making better analysis pipeline

### PR DESCRIPTION
**Pull request by sonyahanson**
Making better automated analysis and storage/plotting of analysis of fluorescence assay data

Starting with 16 spectra datasets: Abl, Src, AblGK, and SrcGK with Bos, Bsi, Gef, Erl.

To start: had to make small change to `select_data` in `platereader.py` so it could also select data from an already made dictionary instead of just an input xml file.

### CODE REVIEW

**Comment by sonyahanson** [comment]
So one advantage of the having `select_data` return a sorted list of values, is that it makes it immediately usable with the current `pymc` modeling framework (below), where 
`Lstated = np.array([20.0e-6,9.15e-6,4.18e-6,1.91e-6,0.875e-6,0.4e-6,0.183e-6,0.0837e-6,0.0383e-6,0.0175e-6,0.008e-6,0.0001e-6], np.float64) # ligand concentration, M`. 

Obviously it would be great to have this be a dictionary with all wells and their corresponding ligand concentration, and I think this shouldn't be too hard to get the pymc modeling to take this in, but maybe that's more appropriate for a later/larger set of changes?

```
pymc_model = pymcmodels.make_model(Pstated, dPstated, Lstated, dLstated, 
               top_complex_fluorescence=CK2_BOS_480,
               top_ligand_fluorescence=CK2_BOS_480_lig,
               use_primary_inner_filter_correction=True, 
               use_secondary_inner_filter_correction=True, 
               assay_volume=assay_volume, DG_prior='uniform')
```

**Comment by jchodera** [comment]
> Obviously it would be great to have this be a dictionary with all wells and their corresponding ligand concentration, and I think this shouldn't be too hard to get the pymc modeling to take this in, but maybe that's more appropriate for a later/larger set of changes?

This is essentially what #41 implements: Each `Well` has attached data on concentrations and measurements. See the [`README.md`](https://github.com/jchodera/assaytools/blob/autoprotocol/data/full_example/README.md#api-notes), which will go into the user guide once this gets cleaned up and merged.

**Comment by sonyahanson** [comment]
Okay. So I might punt on this until the new API is done, then. I would like to make these figures of the results for the 16 spectra relatively soon, but I've got other things I can do in the meantime... 

Maybe I'll change this pull request to be about updating `xml2png.py` so it uses `platereader.py` and is only one script instead of 6 or whatever.

**Comment by jchodera** [comment]
The `xml2png.py` improvements sound great!

Any comments on the [`README.md`](https://github.com/jchodera/assaytools/blob/autoprotocol/data/full_example/README.md#api-notes)?  You can even comment line-by-line if needed.

**Comment by sonyahanson** [comment]
Since I would like to have some data to present at lab meeting next week, I might stick with my original plan for this PR and do some ad hoc analysis without the new API.

**Comment by sonyahanson** [comment]
That was not what I expected would happen. Can I reopen this?

**Comment by sonyahanson** [comment]
Maybe I can't... Will just make a new PR.

**Pull request merged**
