### PR TITLE
Single well for quickmodel and xml2png fix

### PR DESCRIPTION
**Pull request by sonyahanson**
Adding quickmodel single well functionality.

First, though, I'm trying to get the travis build to pass, which is another matplotlib deprecation in xml2png. Hopefully this will now pass, just followed this suggestion: https://stackoverflow.com/questions/44806598/matplotlib-set-color-cycle-versus-set-prop-cycle

### CODE REVIEW

**Comment by sonyahanson** [comment]
If checks pass this should be ready to go! @MehtapIsik does this match what we were talking about?

**Comment by MehtapIsik** [comment]
Thanks a lot @sonyahanson. `inputs_single_well.py` looks very easy to use with this structure. I will try to run an example analysis myself tomorrow and let you know.

**Comment by sonyahanson** [comment]
Do we want to go ahead and merge this?

**Comment by sonyahanson** [comment]
Oh sorry just saw #134 .

**Comment by sonyahanson** [comment]
Hmmm, was going to merge this, but it seems that travis is failing for python3.6  Not sure yet if it's something I did, or rather a more general problem like this: https://github.com/conda/conda/issues/6007

**Comment by jchodera** [comment]
@sonyahanson : I just retriggered the test and everything passes now.

**Comment by sonyahanson** [comment]
Oh sweet thanks!

**Pull request merged**
