### PR TITLE
Add conda-forge channel and remove libgfortran conda deps

### LINKED ISSUE #119: Travis build failing - libgfortran related?
Seems like the travis build is currently failing, potentially because of this line in our conda recipe:
`    - libgfortran ==1.0.0 [linux]`

This is the commit that changed this: https://github.com/choderalab/assaytools/commit/8e6f35eb7bbcf237386248f054a46b2fed1cc90a

Seems like we are no longer pinning the pymc version. Do we have to keep this libgfortran version pinned for some other reason?

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #119

### CODE REVIEW

**Comment by jchodera** [comment]
The current issue seems to be that `pymc` is being picked up from the `anaconda` default channel instead of the `conda-forge` channel:
```
The following NEW packages will be INSTALLED:
    assaytools-dev:  0.1.0-np19py27_0  omnia      
    cairo:           1.12.18-6                    
    fontconfig:      2.11.1-6                     
    freetype:        2.5.5-1                      
    icu:             58.1-1            conda-forge
    libgfortran:     3.0.0-1                      
    libiconv:        1.14-4            conda-forge
    libpng:          1.6.17-0                     
    libxml2:         2.9.4-4           conda-forge
    libxslt:         1.1.29-5          conda-forge
    lxml:            3.8.0-py27_0      conda-forge
    matplotlib:      1.4.3-np19py27_2             
    mkl:             11.3.3-0                     
    numpy:           1.9.3-py27_3                 
    pandas:          0.20.3-py27_1     conda-forge
    pint:            0.8.1-py27_0      conda-forge
    pixman:          0.32.6-0          conda-forge
    py2cairo:        1.10.0-py27_2                
    pymc:            2.3.4-np19py27_0   
```
The default channel `pymc` appears to be incorrectly built because `libgfortran==1` is not provided as a dependency.

**Comment by jchodera** [comment]
Whoops, there's a typo:
```
Error: bad character '=' in package name dependency 'libxslt=1.1.29=2'
```

**Comment by jchodera** [comment]
Whoops: One problem was that we were still building python 3.4, which is no longer supported by conda-forge, so travis was mixing-and-matching conda-forge and default channels.

**Comment by jchodera** [comment]
Woohoo! This passes now.

@sonyahanson can you review and merge?

**Comment by sonyahanson** [comment]
Looks good!

**Pull request merged**
