### PR TITLE
[WIP] Adding emcee to pymc sampler

### PR DESCRIPTION
**Pull request by sonyahanson**
Added a function in `pymcmodels.py` for now.  Added an ipynb where I'm trying to test this. There is currently an error at the end that I think is due to the dimension of the samples being somewhat complicated.

I am following this link, which is for a considerably simpler model: http://twiecki.github.io/blog/2013/09/23/emcee-pymc/

Additionally, I realize I am not using the same sampling scheme as in the original `run_mcmc` function, which has all of the samplers for each parameter defined separately (I believe) with:
```
    mcmc.use_step_method(pymc.Metropolis, getattr(pymc_model, 'DeltaG'), proposal_sd=1.0, proposal_distribution='Normal')
    mcmc.use_step_method(pymc.Metropolis, getattr(pymc_model, 'F_PL'), proposal_sd=10.0, proposal_distribution='Normal')
    mcmc.use_step_method(pymc.Metropolis, getattr(pymc_model, 'F_P'), proposal_sd=10.0, proposal_distribution='Normal')
    mcmc.use_step_method(pymc.Metropolis, getattr(pymc_model, 'F_L'), proposal_sd=10.0, proposal_distribution='Normal')
    mcmc.use_step_method(pymc.Metropolis, getattr(pymc_model, 'F_plate'), proposal_sd=10.0, proposal_distribution='Normal')
    mcmc.use_step_method(pymc.Metropolis, getattr(pymc_model, 'F_buffer'), proposal_sd=10.0, proposal_distribution='Normal')
```
Any suggestions welcome!

### CODE REVIEW

**Comment by jchodera** [comment]
Similar to this?

https://github.com/choderalab/assaytools/blob/master/examples/autoprotocol/single-wavelength-competition-assay-emcee.py#L34-L84

**Comment by sonyahanson** [comment]
Ahh, very similar, indeed, but I'd like to use this to improve our current Bayesian methods. My understanding (and experience) is this autoprotocol branch is not currently working. The structure of the model itself is somewhat different, but maybe this will be useful to look at.

**Comment by jchodera** [comment]
Yes, just hoped it could be a useful template!

Haven't had a chance to return to the autoprotocol branch to debug yet.

**Comment by gregoryross** [comment]
@sonyahanson I've re-written the function to sample the `pymc` model with `emcee`. As several of the `pymc` parameters were vectors and not single values, this required a little extra packing and re-packing. To accompany the new tool, I've written a notebook that compares sampling with `emcee` and `pymc`. Please let me know if you're happy for me to merge.

**Comment by sonyahanson** [comment]
Looks good to me!

**Pull request merged**
